services:
    kernel.listener.preExecute:
        class: AppVentus\Awesome\ShortcutsBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preExecuteController }

    av.tool:
        class: AppVentus\Awesome\ShortcutsBundle\Utils\Utils

    gedmo.urlizer:
        class: Gedmo\Sluggable\Util\Urlizer

    # Form
    form.type.datepicker:
        class: AppVentus\Awesome\ShortcutsBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }
    form.type.datemask:
        class: AppVentus\Awesome\ShortcutsBundle\Form\Type\DatemaskType
        tags:
            - { name: form.type, alias: datemask }
    form.type.datemaskpicker:
        class: AppVentus\Awesome\ShortcutsBundle\Form\Type\DatemaskpickerType
        tags:
            - { name: form.type, alias: datemaskpicker }
    form.type.redactor:
        class: AppVentus\Awesome\ShortcutsBundle\Form\Type\RedactorType
        tags:
            - { name: form.type, alias: redactor }
