services:
    kernel.listener.preExecute:
        class: AppVentus\Awesome\ShortcutsBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preExecuteController }

    av.tool:
        class: AppVentus\Awesome\ShortcutsBundle\Utils\Utils

    gedmo.urlizer:
        class: Gedmo\Sluggable\Util\Urlizer

    # Form
    form.type.datepicker:
        class: AppVentus\Awesome\ShortcutsBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }
