<?php

namespace AppVentus\Awesome\ShortcutsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwesomeRepository extends EntityRepository
{
    function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null,$queryMode=false) {
        if($queryMode){
            $entityPersister = new \AppVentus\AwesomeBundle\Persister\AwesomePersister($this->_em,$this->_class);
            list($query,$params,$type) = $entityPersister->loadAll($criteria, $orderBy, $limit, $offset, $queryMode);
            $query = $this->_em->createQuery($query);
            $query->setParameters($params);
            return $query;
        }else{
            return parent::findBy($criteria, $orderBy, $limit, $offset);
        }
    }
}